// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awsrxupctwlyiknsazzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3c3J4dXBjdHdseWlrbnNhenpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDgwMzQsImV4cCI6MjA2MTMyNDAzNH0.1Myaezeu2WFBP0yGaul0Zg8Ik2OGc04FtKgaptNghOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);